{
 "title": "Hosts: 3.Graph",
 "tags": [
  "GUStat",
  "Hosts",
  "Graph"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "IFace",
    "query": "SHOW TAG VALUES FROM \"net_dev\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"io_disk\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"path\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   { "name": "AGGR", "query": "NONE,MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "graph",
   "description": "Normalized load, averaged over 1, 5, 15 minutes",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"01min_load\") AS \"1min\", ${AGGR}(\"05min_load\") AS \"5min\", ${AGGR}(\"15min_load\") AS \"15min\" FROM \"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Wait\", ${AGGR}(\"SUB_2\") AS \"System\", ${AGGR}(\"SUB_3\") AS \"User\", ${AGGR}(\"SUB_4\") AS \"Nice\", ${AGGR}(\"SUB_5\") AS \"CPU:cores\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"iowait_seconds\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"nice_seconds\"),1s) AS \"SUB_4\", MAX(\"cores_count\") AS \"SUB_5\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"WR:latency\", ${AGGR}(\"SUB_2\") AS \"RD:latency\", 512*${AGGR}(\"SUB_3\") AS \"WR:throughput\", 512*${AGGR}(\"SUB_4\") AS \"RD:throughput\" FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"writes_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"writes_completed_count\")) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"reads_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"reads_completed_count\")) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"writes_sectors_count\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"reads_sectors_count\"),1s) AS \"SUB_4\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Network - TX/RX",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"TX:packets\", ${AGGR}(\"SUB_2\") AS \"RX:packets\", ${AGGR}(\"SUB_3\") AS \"TX:throughput\", ${AGGR}(\"SUB_4\") AS \"RX:throughput\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"tx_packets\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"rx_packets\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"tx_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"rx_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"net_dev\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${AGGR}(\"slab_bytes\") AS \"Slab\", ${AGGR}(\"buffers_bytes\") AS \"Buffers\", ${AGGR}(\"cache_bytes\") AS \"Cache\", MAX(\"total_bytes\")-(${AGGR}(\"slab_bytes\")+${AGGR}(\"buffers_bytes\")+${AGGR}(\"cache_bytes\")+${AGGR}(\"free_bytes\")) AS \"Other\", MAX(\"swap_total_bytes\")-${AGGR}(\"swap_free_bytes\")\n AS \"Swap\", MAX(\"total_bytes\") AS \"Total\" FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND ${timeFilter} GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Proc.Forked\", ${AGGR}(\"SUB_2\") AS \"Ctx.Switch\", ${AGGR}(\"SUB_3\") AS \"Irq.Soft\", ${AGGR}(\"SUB_4\") AS \"Irq.Hard\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"procs_created_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"ctxt_switches_count\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"softirq_count\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"irq_count\"),1s) AS \"SUB_4\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"WR:latency\", ${AGGR}(\"SUB_2\") AS \"RD:latency\", ${AGGR}(\"SUB_3\") AS \"WR:throughput\", ${AGGR}(\"SUB_4\") AS \"RD:throughput\" FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_requested_count\")) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_requested_count\")) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_server_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_server_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Network - Connections",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"udp4_listen_count\")+${AGGR}(\"udp6_listen_count\") AS \"UDP:listen\", ${AGGR}(\"tcp4_listen_count\")+${AGGR}(\"tcp6_listen_count\") AS \"TCP:listen\", ${AGGR}(\"tcp4_established_count\") AS \"TCPv4:established\", ${AGGR}(\"tcp6_established_count\") AS \"TCPv6:established\" FROM \"long\".\"net_conn\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  }
 ]
}