{
 "title": "Hosts: 4b.History (Table)",
 "tags": [
  "GUStat",
  "Hosts",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"history\".\"io_disk\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   {
    "name": "IFace",
    "query": "SHOW TAG VALUES FROM \"history\".\"net_dev\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU / GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Wait",
     "type": "table",
     "description": "I/O wait CPU load ~ time spent (%) waiting for I/O operations to complete",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_iowait_load\") FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "table",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_system_load\") FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "table",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_user_load\") FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - Nice",
     "type": "table",
     "description": "Nice CPU load ~ time spent (%) in (re)niced user space (actual computation)",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_nice_load\") FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "GPU",
     "type": "table",
     "description": "GPU load ~ time spent (%) in each GPU (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 2 },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT LAST(\"${AGGR}_gpu_load\") FROM \"history\".\"gpu\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Unavailable",
     "type": "table",
     "description": "Memory used (not reclaimable)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"MAX_total_bytes\")-LAST(\"${AGGR}_available_bytes\") FROM \"history\".\"mem_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - Used",
     "type": "table",
     "description": "Memory used, including (reclaimable) buffers and cache",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 3 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"MAX_total_bytes\")-LAST(\"${AGGR}_free_bytes\") FROM \"history\".\"mem_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - GPU",
     "type": "table",
     "description": "GPU memory used",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT LAST(\"${AGGR}_mem_used_bytes\") FROM \"history\".\"gpu\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "table",
     "description": "Writes time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_writes_latency_seconds_per_op\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually written to device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT 512*LAST(\"${AGGR}_writes_sectors_per_second\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "table",
     "description": "Writes operations (per second), completed by kernel space",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_writes_completed_per_second\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "table",
     "description": "Reads time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 24 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_reads_latency_seconds_per_op\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually read from device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 24 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT 512*LAST(\"${AGGR}_reads_sectors_per_second\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "table",
     "description": "Reads operations (per second), completed by kernel space",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 24 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_reads_completed_per_second\") FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "table",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 32 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_tx_bytes_per_second\") FROM \"history\".\"net_dev\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "table",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 32 },
     "targets": [
      {
       "alias": "$tag_host:$tag_device",
       "query": "SELECT LAST(\"${AGGR}_rx_bytes_per_second\") FROM \"history\".\"net_dev\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"host\",\"device\""
      }
     ]
    },
    {
     "title": "Network - TCPv4:established",
     "type": "table",
     "description": "Established TCP (IPv4) connections",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 39 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_tcp4_established_count\") FROM \"history\".\"net_conn\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - TCPv6:established",
     "type": "table",
     "description": "Established TCP (IPv6) connections",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 39 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT LAST(\"${AGGR}_tcp6_established_count\") FROM \"history\".\"net_conn\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  }
 ]
}