{
 "title": "Hosts: 1.Heatmap",
 "tags": [
  "GUStat",
  "Hosts",
  "Heatmap"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load - 15min",
     "type": "heatmap",
     "description": "Normalized load, averaged over 15 minutes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"15min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Load - 5min",
     "type": "heatmap",
     "description": "Normalized load, averaged over 5 minutes",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"05min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Load - 1min",
     "type": "heatmap",
     "description": "Normalized load, averaged over 1 minutes",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"01min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Wait",
     "type": "heatmap",
     "description": "I/O wait CPU load ~ time spent (%) waiting for I/O operations to complete, normalized as per CPU cores quantity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"iowait_seconds\"),1s)/MAX(\"cores_count\") AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "heatmap",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.), normalized as per CPU cores quantity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s)/MAX(\"cores_count\") AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "heatmap",
     "description": "User CPU load ~ time spent (%) in user space (actual computation), normalized as per CPU cores quantity",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 3 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s)/MAX(\"cores_count\") AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - Nice",
     "type": "heatmap",
     "description": "Nice CPU load ~ time spent (%) in (re)niced user space (actual computation), normalized as per CPU cores quantity",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 3 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"nice_seconds\"),1s)/MAX(\"cores_count\") AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "GPU",
     "type": "heatmap",
     "description": "GPU load ~ time spent (%) in each GPU (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 3 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT ${AGGR}(\"gpu_load\") FROM \"long\".\"gpu\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Unavailable",
     "type": "heatmap",
     "description": "Memory used (not reclaimable), respective (%) to total memory",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "targets": [
      {
       "query": "SELECT 1-${AGGR}(\"available_bytes\")/MAX(\"total_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - Used",
     "type": "heatmap",
     "description": "Memory used, including (reclaimable) buffers and cache, respective (%) to total memory",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
     "targets": [
      {
       "query": "SELECT 1-${AGGR}(\"free_bytes\")/MAX(\"total_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - Swap",
     "type": "heatmap",
     "description": "Swap memory used, respective (%) to total swap memory",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 4 },
     "targets": [
      {
       "query": "SELECT 1-${AGGR}(\"swap_free_bytes\")/MAX(\"swap_total_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - GPU",
     "type": "heatmap",
     "description": "GPU memory used, respective (%) to total GPU memory",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT ${AGGR}(\"mem_used_bytes\")/MAX(\"mem_total_bytes\") FROM \"long\".\"gpu\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "heatmap",
     "description": "Writes time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"writes_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"writes_completed_count\")) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "heatmap",
     "description": "Writes bytes, actually written to device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "targets": [
      {
       "query": "SELECT 512*${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_sectors_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "heatmap",
     "description": "Writes operations, completed by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_completed_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "heatmap",
     "description": "Reads time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"reads_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"reads_completed_count\")) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "heatmap",
     "description": "Reads bytes, actually read/written from/to device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "targets": [
      {
       "query": "SELECT 512*${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_sectors_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "heatmap",
     "description": "Reads operations, completed by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_completed_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS - WR:latency",
     "type": "heatmap",
     "description": "Writes time spent waiting for server to complete remote procedure calls (RPC)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - WR:throughput",
     "type": "heatmap",
     "description": "Writes bytes, actually sent to server",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 12 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - WR:iops",
     "type": "heatmap",
     "description": "Writes remote procedure calls (RPC), requested from server",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 12 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_write_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:latency",
     "type": "heatmap",
     "description": "Reads time spent waiting for server to complete remote procedure calls (RPC)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:throughput",
     "type": "heatmap",
     "description": "Reads bytes, actually received from server",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:iops",
     "type": "heatmap",
     "description": "Reads remote procedure calls (RPC), requested from server",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_read_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "heatmap",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"tx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"net_dev\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "heatmap",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"net_dev\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - TCPv4:established",
     "type": "heatmap",
     "description": "Established TCP (IPv4) connections",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 20 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"tcp4_established_count\") FROM \"long\".\"net_conn\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - TCPv6:established",
     "type": "heatmap",
     "description": "Established TCP (IPv6) connections",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 20 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"tcp6_established_count\") FROM \"long\".\"net_conn\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  }
 ]
}