{
 "title": "Hosts: 2.Table",
 "tags": [
  "GUStat",
  "Hosts",
  "Table"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"cpu_load\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "IFace",
    "query": "SHOW TAG VALUES FROM \"net_dev\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"io_disk\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"path\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load - 15min",
     "type": "table",
     "description": "Normalized load, averaged over 15 minutes",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"15min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Load - 5min",
     "type": "table",
     "description": "Normalized load, averaged over 5 minutes",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"05min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Load - 1min",
     "type": "table",
     "description": "Normalized load, averaged over 1 minutes",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"01min_load\") FROM \"long\".\"cpu_load\" WHERE \"type\" = 'normalized' AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Wait",
     "type": "table",
     "description": "I/O wait CPU load ~ time spent (%) waiting for I/O operations to complete",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"iowait_seconds\"),1s) AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "table",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s) AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "table",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s) AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - Nice",
     "type": "table",
     "description": "Nice CPU load ~ time spent (%) in (re)niced user space (actual computation)",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"nice_seconds\"),1s) AS \"SUB\" FROM \"long\".\"cpu_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ GROUP BY time(${__interval}),\"host\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Unavailable",
     "type": "table",
     "description": "Memory used (not reclaimable)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT MAX(\"total_bytes\")-${AGGR}(\"available_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - Used",
     "type": "table",
     "description": "Memory used, including (reclaimable) buffers and cache",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT MAX(\"total_bytes\")-${AGGR}(\"free_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - Swap",
     "type": "table",
     "description": "Swap memory used",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 10 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT MAX(\"swap_total_bytes\")-${AGGR}(\"swap_free_bytes\") FROM \"long\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "table",
     "description": "Writes time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"writes_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"writes_completed_count\")) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually written to device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 11 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT 512*(${AGGR}(\"SUB\")) FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_sectors_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "table",
     "description": "Writes operations (per second), completed by kernel space",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 11 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_completed_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "table",
     "description": "Reads time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"reads_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"reads_completed_count\")) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually read from device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 18 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT 512*(${AGGR}(\"SUB\")) FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_sectors_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "table",
     "description": "Reads operations (per second), completed by kernel space",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 18 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_completed_count\"),1s) AS \"SUB\" FROM \"long\".\"io_disk\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "NFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS - WR:latency",
     "type": "table",
     "description": "Writes time spent waiting for server to complete remote procedure calls (RPC)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually sent to server",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - WR:iops",
     "type": "table",
     "description": "Writes remote procedure calls (RPC, per second), requested from server",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_write_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:latency",
     "type": "table",
     "description": "Reads time spent waiting for server to complete remote procedure calls (RPC)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually received from server",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "NFS - RD:iops",
     "type": "table",
     "description": "Reads remote procedure calls (RPC, per second), requested from server",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 12 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_read_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "table",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 13 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"tx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"net_dev\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "table",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 13 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"net_dev\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"host\",\"device\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - TCPv4:established",
     "type": "table",
     "description": "Established TCP (IPv4) connections",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 20 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"tcp4_established_count\") FROM \"long\".\"net_conn\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${IFace}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Network - TCPv6:established",
     "type": "table",
     "description": "Established TCP (IPv6) connections",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 20 },
     "targets": [
      {
       "alias": "$tag_host",
       "query": "SELECT ${AGGR}(\"tcp6_established_count\") FROM \"long\".\"net_conn\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"device\" =~ /^${IFace}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  }
 ]
}