{
 "title": "Hosts: 4a.History (Graph)",
 "tags": [
  "GUStat",
  "Hosts",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"history\".\"cpu_info\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"history\".\"io_disk\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   {
    "name": "IFace",
    "query": "SHOW TAG VALUES FROM \"history\".\"net_dev\" WITH KEY = \"device\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU / GPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Wait",
     "type": "graph",
     "description": "I/O wait CPU load ~ time spent (%) waiting for I/O operations to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_iowait_load\") AS \"MAX\", MEAN(\"MEAN_iowait_load\") AS \"Mean\", MEAN(\"MEDIAN_iowait_load\") AS \"Median\", MIN(\"MIN_iowait_load\") AS \"MIN\" FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "graph",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_system_load\") AS \"MAX\", MEAN(\"MEAN_system_load\") AS \"Mean\", MEAN(\"MEDIAN_system_load\") AS \"Median\", MIN(\"MIN_system_load\") AS \"MIN\" FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "graph",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_user_load\") AS \"MAX\", MEAN(\"MEAN_user_load\") AS \"Mean\", MEAN(\"MEDIAN_user_load\") AS \"Median\", MIN(\"MIN_user_load\") AS \"MIN\" FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - Nice",
     "type": "graph",
     "description": "Nice CPU load ~ time spent (%) in (re)niced user space (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_nice_load\") AS \"MAX\", MEAN(\"MEAN_nice_load\") AS \"Mean\", MEAN(\"MEDIAN_nice_load\") AS \"Median\", MIN(\"MIN_nice_load\") AS \"MIN\" FROM \"history\".\"cpu_info\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "GPU",
     "type": "graph",
     "description": "GPU load ~ time spent (%) in each GPU (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT MAX(\"MAX_gpu_load\") AS \"MAX\", MEAN(\"MEAN_gpu_load\") AS \"Mean\", MEAN(\"MEDIAN_gpu_load\") AS \"Median\", MIN(\"MIN_gpu_load\") AS \"MIN\" FROM \"history\".\"gpu\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - Unavailable",
     "type": "graph",
     "description": "Memory used (not reclaimable)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX\") AS \"MAX\", MEAN(\"Mean\") AS \"Mean\", MEAN(\"Median\") AS \"Median\", MIN(\"MIN\") AS \"MIN\" FROM (SELECT MAX(\"MAX_total_bytes\")-MIN(\"MIN_available_bytes\") AS \"MAX\", MAX(\"MAX_total_bytes\")-MEAN(\"MEAN_available_bytes\") AS \"Mean\", MAX(\"MAX_total_bytes\")-MEAN(\"MEDIAN_available_bytes\") AS \"Median\", MAX(\"MAX_total_bytes\")-MAX(\"MAX_available_bytes\") AS \"MIN\" FROM \"history\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY *) WHERE ${timeFilter} GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - Used",
     "type": "graph",
     "description": "Memory used, including (reclaimable) buffers and cache",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX\") AS \"MAX\", MEAN(\"Mean\") AS \"Mean\", MEAN(\"Median\") AS \"Median\", MIN(\"MIN\") AS \"MIN\" FROM (SELECT MAX(\"MAX_total_bytes\")-MIN(\"MIN_free_bytes\") AS \"MAX\", MAX(\"MAX_total_bytes\")-MEAN(\"MEAN_free_bytes\") AS \"Mean\", MAX(\"MAX_total_bytes\")-MEAN(\"MEDIAN_free_bytes\") AS \"Median\", MAX(\"MAX_total_bytes\")-MAX(\"MAX_free_bytes\") AS \"MIN\" FROM \"history\".\"mem_info\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY *) WHERE ${timeFilter} GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - GPU",
     "type": "graph",
     "description": "GPU memory used",
     "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT MAX(\"MAX_mem_used_bytes\") AS \"MAX\", MEAN(\"MEAN_mem_used_bytes\") AS \"Mean\", MEAN(\"MEDIAN_mem_used_bytes\") AS \"Median\", MIN(\"MIN_mem_used_bytes\") AS \"MIN\" FROM \"history\".\"gpu\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND ${timeFilter} GROUP BY time(${__interval})",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "graph",
     "description": "Writes time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_writes_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_writes_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_writes_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_writes_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "graph",
     "description": "Writes bytes, actually written to device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT 512*MAX(\"MAX_writes_sectors_per_second\") AS \"MAX\", 512*MEAN(\"MEAN_writes_sectors_per_second\") AS \"Mean\", 512*MEAN(\"MEDIAN_writes_sectors_per_second\") AS \"Median\", 512*MIN(\"MIN_writes_sectors_per_second\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "graph",
     "description": "Writes operations, completed by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_writes_completed_per_second\") AS \"MAX\", MEAN(\"MEAN_writes_completed_per_second\") AS \"Mean\", MEAN(\"MEDIAN_writes_completed_per_second\") AS \"Median\", MIN(\"MIN_writes_completed_per_second\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "graph",
     "description": "Reads time spent waiting for device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_reads_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_reads_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_reads_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_reads_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "graph",
     "description": "Reads bytes, actually read from device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT 512*MAX(\"MAX_reads_sectors_per_second\") AS \"MAX\", 512*MEAN(\"MEAN_reads_sectors_per_second\") AS \"Mean\", 512*MEAN(\"MEDIAN_reads_sectors_per_second\") AS \"Median\", 512*MIN(\"MIN_reads_sectors_per_second\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "graph",
     "description": "Reads operations, completed by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_reads_completed_per_second\") AS \"MAX\", MEAN(\"MEAN_reads_completed_per_second\") AS \"Mean\", MEAN(\"MEDIAN_reads_completed_per_second\") AS \"Median\", MIN(\"MIN_reads_completed_per_second\") AS \"MIN\" FROM \"history\".\"io_disk\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "graph",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_tx_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_tx_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_tx_bytes_per_second\") AS \"Median\", MIN(\"MIN_tx_bytes_per_second\") AS \"MIN\" FROM \"history\".\"net_dev\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "graph",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rx_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_rx_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rx_bytes_per_second\") AS \"Median\", MIN(\"MIN_rx_bytes_per_second\") AS \"MIN\" FROM \"history\".\"net_dev\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Network - TCPv4:established",
     "type": "graph",
     "description": "Established TCP (IPv4) connections",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_tcp4_established_count\") AS \"MAX\", MEAN(\"MEAN_tcp4_established_count\") AS \"Mean\", MEAN(\"MEDIAN_tcp4_established_count\") AS \"Median\", MIN(\"MIN_tcp4_established_count\") AS \"MIN\" FROM \"history\".\"net_conn\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Network - TCPv6:established)",
     "type": "graph",
     "description": "Established TCP (IPv6) connections",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_tcp6_established_count\") AS \"MAX\", MEAN(\"MEAN_tcp6_established_count\") AS \"Mean\", MEAN(\"MEDIAN_tcp6_established_count\") AS \"Median\", MIN(\"MIN_tcp6_established_count\") AS \"MIN\" FROM \"history\".\"net_conn\" WHERE ${timeFilter} AND \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  }
 ]
}