{
 "title": "NFS: 4b.History (Table)",
 "tags": [
  "GUStat",
  "NFS",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"history\".\"io_mount_nfs\" WITH KEY = \"path\""
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS: WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually sent to server",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_io_writes_server_bytes_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "NFS: RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually received from server",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_io_reads_server_bytes_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC - Write:latency",
     "type": "table",
     "description": "Write RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_write_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Write:iops",
     "type": "table",
     "description": "Write RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_write_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Read:latency",
     "type": "table",
     "description": "Read RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_read_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Read:iops",
     "type": "table",
     "description": "Read RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_read_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Create:latency",
     "type": "table",
     "description": "Create (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_create_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Create:iops",
     "type": "table",
     "description": "Create (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_create_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Remove:latency",
     "type": "table",
     "description": "Remove (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_remove_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Remove:iops",
     "type": "table",
     "description": "Remove (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_remove_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Mkdir:latency",
     "type": "table",
     "description": "Mkdir (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_mkdir_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Mkdir:iops",
     "type": "table",
     "description": "Mkdir (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_mkdir_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Rmdir:latency",
     "type": "table",
     "description": "Rmdir (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 44 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_rmdir_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Rmdir:iops",
     "type": "table",
     "description": "Rmdir (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 44 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_rmdir_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Readdir:latency",
     "type": "table",
     "description": "Readdir (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_readdir_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Readdir:iops",
     "type": "table",
     "description": "Readdir (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 51 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_readdir_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC - Readdir+:latency",
     "type": "table",
     "description": "Readdir+ (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 58 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_readdirplus_latency_seconds_per_op\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    },
    {
     "title": "RPC: Readdir+:iops",
     "type": "table",
     "description": "Readdir+ (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 58 },
     "targets": [
      {
       "alias": "$tag_path",
       "query": "SELECT LAST(\"${AGGR}_rpc_readdirplus_requested_per_second\") FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"path\""
      }
     ]
    }
   ]
  }
 ]
}