{
 "title": "NFS: 3.Graph",
 "tags": [
  "GUStat",
  "NFS",
  "Graph"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"path\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   { "name": "AGGR", "query": "NONE,MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NFS - WR+RD:throughput+iops",
   "type": "graph",
   "description": "Writes/reads bytes/operations (per second), actually sent/received to/from server",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"WR:iops\", ${AGGR}(\"SUB_2\") AS \"RD:iops\", ${AGGR}(\"SUB_3\") AS \"WR:throughput\", ${AGGR}(\"SUB_4\") AS \"RD:throughput\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_write_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_read_requested_count\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_server_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_server_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Write:latency+iops",
   "type": "graph",
   "description": "Write RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Write:iops\", ${AGGR}(\"SUB_2\") AS \"Write:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_write_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Create:latency+iops",
   "type": "graph",
   "description": "Create (file) RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Create:iops\", ${AGGR}(\"SUB_2\") AS \"Create:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_create_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_create_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_create_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Mkdir:latency+iops",
   "type": "graph",
   "description": "Create (directory) RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Mkdir:iops\", ${AGGR}(\"SUB_2\") AS \"Mkdir:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_mkdir_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_mkdir_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_mkdir_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Readdir:latency+iops",
   "type": "graph",
   "description": "List directory RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Readdir:iops\", ${AGGR}(\"SUB_2\") AS \"Readdir:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_readdir_requested_count\"),1s)+NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_readdirplus_requested_count\"),1s) AS \"SUB_1\", (NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_readdir_elapsed_total_seconds\"))+NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_readdirplus_elapsed_total_seconds\")))/(NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_readdir_requested_count\"))+NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_readdirplus_requested_count\"))) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Read:latency+iops",
   "type": "graph",
   "description": "Read RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Read:iops\", ${AGGR}(\"SUB_2\") AS \"Read:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_read_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Remove:latency+iops",
   "type": "graph",
   "description": "Remove (file) RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Remove:iops\", ${AGGR}(\"SUB_2\") AS \"Remove:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_remove_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_remove_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_remove_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "NFS - Rmdir:latency+iops",
   "type": "graph",
   "description": "Remove (directory) RPC time spent waiting for RPC to complete, and operations (per second)",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Rmdir:iops\", ${AGGR}(\"SUB_2\") AS \"Rmdir:latency\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_rmdir_requested_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_rmdir_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_rmdir_requested_count\")) AS \"SUB_2\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  }
 ]
}