{
 "title": "NFS: 2.Table",
 "tags": [
  "GUStat",
  "NFS",
  "Table"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"io_mount_nfs\" WITH KEY = \"path\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS: WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually sent to server",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "NFS: RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually received from server",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_server_bytes\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC - Write:latency",
     "type": "table",
     "description": "Write RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_write_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC: Write:iops",
     "type": "table",
     "description": "Write RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_write_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC - Read:latency",
     "type": "table",
     "description": "Read RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_read_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC: Read:iops",
     "type": "table",
     "description": "Read RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_read_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC - Create:latency",
     "type": "table",
     "description": "Create (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_create_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_create_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC: Create:iops",
     "type": "table",
     "description": "Create (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 23 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_create_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC - Remove:latency",
     "type": "table",
     "description": "Remove (file) RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_remove_elapsed_total_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"rpc_remove_requested_count\")) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    },
    {
     "title": "RPC: Remove:iops",
     "type": "table",
     "description": "Remove (file) RPC operations (per second)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
     "targets": [
      {
       "alias": "$tag_host:$tag_path",
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rpc_remove_requested_count\"),1s) AS \"SUB\" FROM \"long\".\"io_mount_nfs\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval}),\"host\",\"path\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\",\"path\""
      }
     ]
    }
   ]
  }
 ]
}