{
 "title": "NFS: 4a.History (Graph)",
 "tags": [
  "GUStat",
  "NFS",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Export",
    "query": "SHOW TAG VALUES FROM \"history\".\"io_mount_nfs\" WITH KEY = \"path\""
   }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "NFS - WR:throughput",
     "type": "graph",
     "description": "Writes bytes (per second), actually sent to server",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_writes_server_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_io_writes_server_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_writes_server_bytes_per_second\") AS \"Median\", MIN(\"MIN_io_writes_server_bytes_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "NFS - RD:throughput",
     "type": "graph",
     "description": "Reads bytes (per second), actually received from server",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_reads_server_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_io_reads_server_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_reads_server_bytes_per_second\") AS \"Median\", MIN(\"MIN_io_reads_server_bytes_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "RPCs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC - Write:latency",
     "type": "graph",
     "description": "Write RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_write_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_write_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_write_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_write_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Write:iops",
     "type": "graph",
     "description": "Write RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_write_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_write_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_write_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_write_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Read:latency",
     "type": "graph",
     "description": "Read RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_read_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_read_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_read_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_read_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Read:iops",
     "type": "graph",
     "description": "Read RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_read_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_read_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_read_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_read_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Create:latency",
     "type": "graph",
     "description": "Create RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_create_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_create_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_create_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_create_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Create:iops",
     "type": "graph",
     "description": "Create RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_create_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_create_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_create_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_create_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Remove:latency",
     "type": "graph",
     "description": "Remove RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_remove_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_remove_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_remove_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_remove_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Remove:iops",
     "type": "graph",
     "description": "Remove RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_remove_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_remove_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_remove_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_remove_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Mkdir:latency",
     "type": "graph",
     "description": "Mkdir RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_mkdir_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_mkdir_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_mkdir_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_mkdir_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Mkdir:iops",
     "type": "graph",
     "description": "Mkdir RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_mkdir_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_mkdir_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_mkdir_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_mkdir_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Rmdir:latency",
     "type": "graph",
     "description": "Rmdir RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_rmdir_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_rmdir_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_rmdir_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_rmdir_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Rmdir:iops",
     "type": "graph",
     "description": "Rmdir RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 38 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_rmdir_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_rmdir_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_rmdir_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_rmdir_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Readdir:latency",
     "type": "graph",
     "description": "Readdir RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_readdir_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_readdir_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_readdir_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_readdir_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Readdir:iops",
     "type": "graph",
     "description": "Readdir RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 45 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_readdir_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_readdir_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_readdir_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_readdir_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Readdir+:latency",
     "type": "graph",
     "description": "Readdir+ RPC time spent waiting for RPC to complete",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_readdirplus_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_rpc_readdirplus_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_rpc_readdirplus_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_rpc_readdirplus_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "RPC - Readdir+:iops",
     "type": "graph",
     "description": "Readdir+ RPC operations (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 52 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rpc_readdirplus_requested_per_second\") AS \"MAX\", MEAN(\"MEAN_rpc_readdirplus_requested_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rpc_readdirplus_requested_per_second\") AS \"Median\", MIN(\"MIN_rpc_readdirplus_requested_per_second\") AS \"MIN\" FROM \"history\".\"io_mount_nfs\" WHERE ${timeFilter} AND \"path\" =~ /^${Export}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  }
 ]
}