{
 "title": "Procs: 3.Graph",
 "tags": [
  "GUStat",
  "Procs",
  "Graph"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "User",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"user_uid_real\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   { "name": "AGGR", "query": "NONE,MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 18, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"System\", ${AGGR}(\"SUB_2\") AS \"User\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"cpu_stime_seconds\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"cpu_utime_seconds\"),1s) AS \"SUB_2\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Memory - RSS/VSZ",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"mem_rss_bytes\") AS \"RSS\", ${AGGR}(\"mem_rss_peak_bytes\") AS \"RSS:peak\", ${AGGR}(\"mem_vsize_bytes\") AS \"VSZ\", ${AGGR}(\"mem_vsize_peak_bytes\") AS \"VSZ:peak\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ AND ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "I/O - WR",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"WR:iops\", ${AGGR}(\"SUB_2\") AS \"WR:throughput\", ${AGGR}(\"SUB_3\") AS \"WR:volume\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_syscalls_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_bytes\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_chars\"),1s) AS \"SUB_3\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Mem.MinFlt\", ${AGGR}(\"SUB_2\") AS \"Mem.MajFlt\", ${AGGR}(\"SUB_3\") AS \"Sched.VolCtxSwi\", ${AGGR}(\"SUB_4\") AS \"Sched.NonVolCtxSwi\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"mem_minflt_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"mem_majflt_count\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"sched_ctx_vol_switches_count\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"sched_ctx_nonvol_switches_count\"),1s) AS \"SUB_4\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Memory - Objects",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"mem_executable_bytes\") AS \"Executable\", ${AGGR}(\"mem_libraries_bytes\") AS \"Libraries\", ${AGGR}(\"mem_stack_bytes\") AS \"Stack\", ${AGGR}(\"mem_data_bytes\") AS \"Data\", ${AGGR}(\"mem_swapped_bytes\") AS \"Swap\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ AND ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "I/O - RD",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"RD:iops\", ${AGGR}(\"SUB_2\") AS \"RD:throughput\", ${AGGR}(\"SUB_3\") AS \"RD:volume\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_syscalls_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_bytes\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_chars\"),1s) AS \"SUB_3\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  }
 ]
}