{
 "title": "Procs: 4b.History (Table)",
 "tags": [
  "GUStat",
  "Procs",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "User",
    "query": "SHOW TAG VALUES FROM \"history\".\"proc_stat\" WITH KEY = \"user_uid_real\""
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - System",
     "type": "table",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_cpu_stime_load\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "table",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_cpu_utime_load\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel - NonVolCtxSwi",
     "type": "table",
     "description": "Non-voluntary context switches (per second), preempted by kernel space",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_sched_ctxt_nonvol_switches_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "Kernel - VolCtxSwi",
     "type": "table",
     "description": "Voluntary context switches (per second), as requested by user space",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_sched_ctxt_vol_switches_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "table",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_mem_majflt_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "Memory - MinFlt",
     "type": "table",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_mem_minflt_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "table",
     "description": "Resident set size (RSS), using actual RAM",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_mem_rss_bytes\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "Memory - VSZ",
     "type": "table",
     "description": "Allocated virtual size (VSZ), including swap and memory-mapped files",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_mem_vsize_bytes\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_writes_bytes_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "I/O - WR:volume",
     "type": "table",
     "description": "Writes bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_writes_chars_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "I/O - WR:iops",
     "type": "table",
     "description": "Writes operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_writes_syscalls_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "I/O - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_reads_bytes_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "I/O - RD:volume",
     "type": "table",
     "description": "Reads bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_reads_chars_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    },
    {
     "title": "I/O - RD:iops",
     "type": "table",
     "description": "Reads operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
     "targets": [
      {
       "alias": "$tag_user_uid_real",
       "query": "SELECT LAST(\"${AGGR}_io_reads_syscalls_per_second\") FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"user_uid_real\""
      }
     ]
    }
   ]
  }
 ]
}