{
 "title": "Procs: 1.Heatmap",
 "tags": [
  "GUStat",
  "Procs",
  "Heatmap"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Task",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"task\""
   },
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"serie\" WHERE \"task\" =~ /^${Task}$/"
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"host\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "User",
    "query": "SHOW TAG VALUES FROM \"proc_stat\" WITH KEY = \"user_uid_real\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - System",
     "type": "heatmap",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"cpu_stime_seconds\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "heatmap",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"cpu_utime_seconds\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel - NonVolCtxSwi",
     "type": "heatmap",
     "description": "Non-voluntary context switches (per second), preempted by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"sched_ctxt_nonvol_switches_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Kernel - VolCtxSwi",
     "type": "heatmap",
     "description": "Voluntary context switches (per second), as requested by user space",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"sched_ctxt_vol_switches_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "heatmap",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"mem_majflt_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - MinFlt",
     "type": "heatmap",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"mem_minflt_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "heatmap",
     "description": "Resident set size (RSS), using actual RAM",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"mem_rss_bytes\") FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "Memory - VSZ",
     "type": "heatmap",
     "description": "Allocated virtual size (VSZ), including swap and memory-mapped files",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"mem_vsize_bytes\") FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O - WR:throughput",
     "type": "heatmap",
     "description": "Writes bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_bytes\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "I/O - WR:volume",
     "type": "heatmap",
     "description": "Writes bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_chars\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "I/O - WR:iops",
     "type": "heatmap",
     "description": "Writes operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_writes_syscalls_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "I/O - RD:throughput",
     "type": "heatmap",
     "description": "Reads bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_bytes\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "I/O - RD:volume",
     "type": "heatmap",
     "description": "Reads bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_chars\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    },
    {
     "title": "I/O - RD:iops",
     "type": "heatmap",
     "description": "Reads operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"io_reads_syscalls_count\"),1s) AS \"SUB\" FROM \"short\".\"proc_stat\" WHERE \"task\" =~ /^${Task}$/ AND \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval}),\"host\",\"pid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"host\""
      }
     ]
    }
   ]
  }
 ]
}