{
 "title": "Procs: 4a.History (Graph)",
 "tags": [
  "GUStat",
  "Procs",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "User",
    "query": "SHOW TAG VALUES FROM \"history\".\"proc_stat\" WITH KEY = \"user_uid_real\""
   }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - System",
     "type": "graph",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_cpu_stime_load\") AS \"MAX\", MEAN(\"MEAN_cpu_stime_load\") AS \"Mean\", MEAN(\"MEDIAN_cpu_stime_load\") AS \"Median\", MIN(\"MIN_cpu_stime_load\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "graph",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_cpu_utime_load\") AS \"MAX\", MEAN(\"MEAN_cpu_utime_load\") AS \"Mean\", MEAN(\"MEDIAN_cpu_utime_load\") AS \"Median\", MIN(\"MIN_cpu_utime_load\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kernel - NonVolCtxSwi",
     "type": "graph",
     "description": "Non-voluntary context switches (per second), preempted by kernel space",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_sched_ctxt_nonvol_switches_per_second\") AS \"MAX\", MEAN(\"MEAN_sched_ctxt_nonvol_switches_per_second\") AS \"Mean\", MEAN(\"MEDIAN_sched_ctxt_nonvol_switches_per_second\") AS \"Median\", MIN(\"MIN_sched_ctxt_nonvol_switches_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Kernel - VolCtxSwi",
     "type": "graph",
     "description": "Voluntary context switches (per second), as requested by user space",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_sched_ctxt_nonvol_switches_per_second\") AS \"MAX\", MEAN(\"MEAN_sched_ctxt_nonvol_switches_per_second\") AS \"Mean\", MEAN(\"MEDIAN_sched_ctxt_nonvol_switches_per_second\") AS \"Median\", MIN(\"MIN_sched_ctxt_nonvol_switches_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "graph",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_mem_majflt_per_second\") AS \"MAX\", MEAN(\"MEAN_mem_majflt_per_second\") AS \"Mean\", MEAN(\"MEDIAN_mem_majflt_per_second\") AS \"Median\", MIN(\"MIN_mem_majflt_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - MinFlt",
     "type": "graph",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_mem_minflt_per_second\") AS \"MAX\", MEAN(\"MEAN_mem_minflt_per_second\") AS \"Mean\", MEAN(\"MEDIAN_mem_minflt_per_second\") AS \"Median\", MIN(\"MIN_mem_minflt_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "graph",
     "description": "Resident set size (RSS), using actual RAM",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_mem_rss_bytes\") AS \"MAX\", MEAN(\"MEAN_mem_rss_bytes\") AS \"Mean\", MEAN(\"MEDIAN_mem_rss_bytes\") AS \"Median\", MIN(\"MIN_mem_rss_bytes\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - VSZ",
     "type": "graph",
     "description": "Allocated virtual size (VSZ), including swap and memory-mapped files",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_mem_vsize_bytes\") AS \"MAX\", MEAN(\"MEAN_mem_vsize_bytes\") AS \"Mean\", MEAN(\"MEDIAN_mem_vsize_bytes\") AS \"Median\", MIN(\"MIN_mem_vsize_bytes\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "I/O - WR:throughput",
     "type": "graph",
     "description": "Writes bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_writes_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_io_writes_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_writes_bytes_per_second\") AS \"Median\", MIN(\"MIN_io_writes_bytes_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "I/O - WR:volume",
     "type": "graph",
     "description": "Writes bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_writes_chars_per_second\") AS \"MAX\", MEAN(\"MEAN_io_writes_chars_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_writes_chars_per_second\") AS \"Median\", MIN(\"MIN_io_writes_chars_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "I/O - WR:iops",
     "type": "graph",
     "description": "Writes operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_writes_syscalls_per_second\") AS \"MAX\", MEAN(\"MEAN_io_writes_syscalls_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_writes_syscalls_per_second\") AS \"Median\", MIN(\"MIN_io_writes_syscalls_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "I/O - RD:throughput",
     "type": "graph",
     "description": "Reads bytes (per second), requiring I/O (storage) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_reads_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_io_reads_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_reads_bytes_per_second\") AS \"Median\", MIN(\"MIN_io_reads_bytes_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "I/O - RD:volume",
     "type": "graph",
     "description": "Reads bytes (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_reads_chars_per_second\") AS \"MAX\", MEAN(\"MEAN_io_reads_chars_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_reads_chars_per_second\") AS \"Median\", MIN(\"MIN_io_reads_chars_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "I/O - RD:iops",
     "type": "graph",
     "description": "Reads operations (per second), including (memory) cache, TTYs, etc.",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_io_reads_syscalls_per_second\") AS \"MAX\", MEAN(\"MEAN_io_reads_syscalls_per_second\") AS \"Mean\", MEAN(\"MEDIAN_io_reads_syscalls_per_second\") AS \"Median\", MIN(\"MIN_io_reads_syscalls_per_second\") AS \"MIN\" FROM \"history\".\"proc_stat\" WHERE ${timeFilter} AND \"user_uid_real\" =~ /^${User}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  }
 ]
}