{
 "title": "VMs: 3.Graph",
 "tags": [
  "GUStat",
  "VMs",
  "Graph"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"virt_cpu\" WITH KEY = \"serie\""
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"virt_cpu\" WITH KEY = \"host\" WHERE \"serie\" =~ /^${Serie}$/"
   },
   {
    "name": "Guest",
    "query": "SHOW TAG VALUES FROM \"virt_cpu\" WITH KEY = \"guest\" WHERE \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/"
   },
   {
    "name": "Disk",
    "query": "SHOW TAG VALUES FROM \"virt_io\" WITH KEY = \"device\" WHERE \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/"
   },
   {
    "name": "IFace",
    "query": "SHOW TAG VALUES FROM \"virt_net\" WITH KEY = \"device\" WHERE \"serie\" =~ /^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/"
   },
   { "name": "AGGR", "query": "NONE,MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"Host:system\", ${AGGR}(\"SUB_2\") AS \"Host:user\", ${AGGR}(\"SUB_3\") AS \"Guest\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"total_seconds\"),1s)-NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s)-NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s) AS \"SUB_3\" FROM \"long\".\"virt_cpu\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~/^${Host}$/ AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory - RSS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${AGGR}(\"rss_bytes\") AS \"RSS\", MAX(\"current_bytes\") AS \"Total\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/ AND ${timeFilter} GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"WR:latency\", ${AGGR}(\"SUB_2\") AS \"RD:latency\", ${AGGR}(\"SUB_3\") AS \"WR:throughput\", ${AGGR}(\"SUB_4\") AS \"RD:throughput\" FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"writes_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"writes_ops_count\")) AS \"SUB_1\", NON_NEGATIVE_DIFFERENCE(LAST(\"reads_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"reads_ops_count\")) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"writes_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"reads_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/ AND \"device\" =~ /^${Disk}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"TX:pkts\", ${AGGR}(\"SUB_2\") AS \"RX:pkts\", ${AGGR}(\"SUB_3\") AS \"TX:throughput\", ${AGGR}(\"SUB_4\") AS \"RX:throughput\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"tx_packets\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"rx_packets\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"tx_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"rx_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"virt_net\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/ AND \"device\" =~ /^${IFace}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval})"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT ${AGGR}(\"SUB_1\") AS \"MajFlt\", ${AGGR}(\"SUB_2\") AS \"MinFlt\", ${AGGR}(\"SUB_3\") AS \"WR:throughput\", ${AGGR}(\"SUB_4\") AS \"RD:throughput\" FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"majflt_count\"),1s) AS \"SUB_1\", NON_NEGATIVE_DERIVATIVE(LAST(\"minflt_count\"),1s) AS \"SUB_2\", NON_NEGATIVE_DERIVATIVE(LAST(\"swap_writes_bytes\"),1s) AS \"SUB_3\", NON_NEGATIVE_DERIVATIVE(LAST(\"swap_reads_bytes\"),1s) AS \"SUB_4\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND \"guest\" =~ /^${Guest}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"guest\")  GROUP BY time(${__interval})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}