{
 "title": "VMs: 4b.History (Table)",
 "tags": [
  "GUStat",
  "VMs",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Guest",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_cpu\" WITH KEY = \"guest\""
   },
   {
    "name": "DiskId",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_io\" WITH KEY = \"devid\" WHERE \"guest\" =~ /^${Guest}$/"
   },
   {
    "name": "IFaceId",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_net\" WITH KEY = \"devid\" WHERE \"guest\" =~ /^${Guest}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Total",
     "type": "table",
     "description": "Total CPU load ~ time spent (%) scheduling the guest",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_total_load\") FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "table",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 2 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_system_load\") FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "table",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 2 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_user_load\") FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "table",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_majflt_per_second\") FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Memory - MinFlt",
     "type": "table",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_minflt_per_second\") FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "table",
     "description": "Memory resident set size (RSS)",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_rss_bytes\") FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Swap - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), actually written to swap memory",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_swap_writes_bytes_per_second\") FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Swap - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), actually read from swap memory",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
     "targets": [
      {
       "alias": "$tag_guest",
       "query": "SELECT LAST(\"${AGGR}_swap_reads_bytes_per_second\") FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "table",
     "description": "Writes time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_writes_latency_seconds_per_op\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "table",
     "description": "Writes bytes (per second), written to virtual device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_writes_bytes_per_second\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "table",
     "description": "Writes operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 10 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_writes_ops_per_second\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "table",
     "description": "Reads time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_reads_latency_seconds_per_op\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "table",
     "description": "Reads bytes (per second), read from virtual device",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_reads_bytes_per_second\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "table",
     "description": "Reads operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_reads_ops_per_second\") FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "table",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_tx_bytes_per_second\") FROM \"history\".\"virt_net\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${IFaceId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "table",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 25 },
     "targets": [
      {
       "alias": "$tag_guest:$tag_devid",
       "query": "SELECT LAST(\"${AGGR}_rx_bytes_per_second\") FROM \"history\".\"virt_net\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${IFaceId}$/ GROUP BY time(${__interval}),\"guest\",\"devid\""
      }
     ]
    }
   ]
  }
 ]
}