{
 "title": "VMs: 1.Heatmap",
 "tags": [
  "GUStat",
  "VMs",
  "Heatmap"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Serie",
    "query": "SHOW TAG VALUES FROM \"virt_cpu\" WITH KEY = \"serie\""
   },
   {
    "name": "Host",
    "query": "SHOW TAG VALUES FROM \"virt_cpu\" WITH KEY = \"host\" WHERE \"serie\" =~ /^${Serie}$/"
   },
   { "name": "AGGR", "query": "MAX,MEAN,MEDIAN,MIN,SUM" }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Total",
     "type": "heatmap",
     "description": "Total CPU load ~ time spent (%) scheduling the guest, normalized as per vCPU quantity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"total_seconds\"),1s)/MAX(\"vcpu_count\") AS \"SUB\" FROM \"long\".\"virt_cpu\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~/^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "heatmap",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.), normalized as per vCPU quantity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"system_seconds\"),1s)/MAX(\"vcpu_count\") AS \"SUB\" FROM \"long\".\"virt_cpu\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~/^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "heatmap",
     "description": "User CPU load ~ time spent (%) in user space (actual computation), normalized as per vCPU quantity",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"user_seconds\"),1s)/MAX(\"vcpu_count\") AS \"SUB\" FROM \"long\".\"virt_cpu\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~/^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "heatmap",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"majflt_count\"),1s) AS \"SUB\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Memory - MinjFlt",
     "type": "heatmap",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"minflt_count\"),1s) AS \"SUB\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "heatmap",
     "description": "Memory resident set size (RSS), respective (%) to total memory",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"rss_bytes\")/MAX(\"current_bytes\") AS \"RSS\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ AND ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Swap - WR:throughput",
     "type": "heatmap",
     "description": "Writes bytes (per second), actually written to swap memory",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"swap_writes_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Swap - RD:throughput",
     "type": "heatmap",
     "description": "Reads bytes (per second), actually read from swap memory",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"swap_reads_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_mem\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "heatmap",
     "description": "Writes time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"writes_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"writes_ops_count\")) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "heatmap",
     "description": "Writes bytes (per second), written to virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "heatmap",
     "description": "Writes operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"writes_ops_count\"),1s) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "heatmap",
     "description": "Reads time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DIFFERENCE(LAST(\"reads_elapsed_seconds\"))/NON_NEGATIVE_DIFFERENCE(LAST(\"reads_ops_count\")) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "heatmap",
     "description": "Reads bytes (per second), read from virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "heatmap",
     "description": "Reads operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"reads_ops_count\"),1s) AS \"SUB\" FROM \"long\".\"virt_io\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "heatmap",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"tx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_net\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "heatmap",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "targets": [
      {
       "query": "SELECT ${AGGR}(\"SUB\") FROM (SELECT NON_NEGATIVE_DERIVATIVE(LAST(\"rx_bytes\"),1s) AS \"SUB\" FROM \"long\".\"virt_net\" WHERE \"serie\" =~/^${Serie}$/ AND \"host\" =~ /^${Host}$/ GROUP BY time(${__interval}),\"guest\",\"devid\") WHERE ${timeFilter} GROUP BY time(${__interval}),\"guest\""
      }
     ]
    }
   ]
  }
 ]
}