{
 "title": "VMs: 4a.History (Graph)",
 "tags": [
  "GUStat",
  "VMs",
  "History"
 ],
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Guest",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_cpu\" WITH KEY = \"guest\""
   },
   {
    "name": "DiskId",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_io\" WITH KEY = \"devid\" WHERE \"guest\" =~ /^${Guest}$/"
   },
   {
    "name": "IFaceId",
    "query": "SHOW TAG VALUES FROM \"history\".\"virt_net\" WITH KEY = \"devid\" WHERE \"guest\" =~ /^${Guest}$/"
   }
  ]
 },
 "panels": [
  { "title": "Jump To...", "type": "text", "gridPos": { "h": 1, "w": 2, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Total",
     "type": "graph",
     "description": "Total CPU load ~ time spent (%) scheduling the guest",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_total_load\") AS \"MAX\", MEAN(\"MEAN_total_load\") AS \"Mean\", MEAN(\"MEDIAN_total_load\") AS \"Median\", MIN(\"MIN_total_load\") AS \"MIN\" FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - System",
     "type": "graph",
     "description": "System CPU load ~ time spent (%) in kernel space (I/Os, device drivers, etc.)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_system_load\") AS \"MAX\", MEAN(\"MEAN_system_load\") AS \"Mean\", MEAN(\"MEDIAN_system_load\") AS \"Median\", MIN(\"MIN_system_load\") AS \"MIN\" FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "CPU - User",
     "type": "graph",
     "description": "User CPU load ~ time spent (%) in user space (actual computation)",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_user_load\") AS \"MAX\", MEAN(\"MEAN_user_load\") AS \"Mean\", MEAN(\"MEDIAN_user_load\") AS \"Median\", MIN(\"MIN_user_load\") AS \"MIN\" FROM \"history\".\"virt_cpu\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory - MajFlt",
     "type": "graph",
     "description": "Major memory faults (per second), requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_majflt_per_second\") AS \"MAX\", MEAN(\"MEAN_majflt_per_second\") AS \"Mean\", MEAN(\"MEDIAN_majflt_per_second\") AS \"Median\", MIN(\"MIN_majflt_per_second\") AS \"MIN\" FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - MinFlt",
     "type": "graph",
     "description": "Minor memory faults (per second), not requiring I/O (swap) activity",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_minflt_per_second\") AS \"MAX\", MEAN(\"MEAN_minflt_per_second\") AS \"Mean\", MEAN(\"MEDIAN_minflt_per_second\") AS \"Median\", MIN(\"MIN_minflt_per_second\") AS \"MIN\" FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Memory - RSS",
     "type": "graph",
     "description": "Memory resident set size (RSS)",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rss_bytes\") AS \"MAX\", MEAN(\"MEAN_rss_bytes\") AS \"Mean\", MEAN(\"MEDIAN_rss_bytes\") AS \"Median\", MIN(\"MIN_rss_bytes\") AS \"MIN\" FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Swap - WR:throughput",
     "type": "graph",
     "description": "Writes bytes (per second), actually written to swap memory",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_swap_writes_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_swap_writes_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_swap_writes_bytes_per_second\") AS \"Median\", MIN(\"MIN_swap_writes_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Swap - RD:throughput",
     "type": "graph",
     "description": "Reads bytes (per second), actually written to swap memory",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_swap_reads_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_swap_reads_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_swap_reads_bytes_per_second\") AS \"Median\", MIN(\"MIN_swap_reads_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_mem\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk - WR:latency",
     "type": "graph",
     "description": "Writes time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_writes_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_writes_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_writes_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_writes_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - WR:throughput",
     "type": "graph",
     "description": "Writes bytes (per second), written to virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 10 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_writes_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_writes_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_writes_bytes_per_second\") AS \"Median\", MIN(\"MIN_writes_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - WR:iops",
     "type": "graph",
     "description": "Writes operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_writes_ops_per_second\") AS \"MAX\", MEAN(\"MEAN_writes_ops_per_second\") AS \"Mean\", MEAN(\"MEDIAN_writes_ops_per_second\") AS \"Median\", MIN(\"MIN_writes_ops_per_second\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:latency",
     "type": "graph",
     "description": "Reads time spent waiting for virtual device to complete operations",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_reads_latency_seconds_per_op\") AS \"MAX\", MEAN(\"MEAN_reads_latency_seconds_per_op\") AS \"Mean\", MEAN(\"MEDIAN_reads_latency_seconds_per_op\") AS \"Median\", MIN(\"MIN_reads_latency_seconds_per_op\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:throughput",
     "type": "graph",
     "description": "Reads bytes (per second), written to virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_reads_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_reads_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_reads_bytes_per_second\") AS \"Median\", MIN(\"MIN_reads_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Disk - RD:iops",
     "type": "graph",
     "description": "Reads operations (per second), performed on virtual device",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_reads_ops_per_second\") AS \"MAX\", MEAN(\"MEAN_reads_ops_per_second\") AS \"Mean\", MEAN(\"MEDIAN_reads_ops_per_second\") AS \"Median\", MIN(\"MIN_reads_ops_per_second\") AS \"MIN\" FROM \"history\".\"virt_io\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${DiskId}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network - TX:throughput",
     "type": "graph",
     "description": "Transmitted bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_tx_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_tx_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_tx_bytes_per_second\") AS \"Median\", MIN(\"MIN_tx_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_net\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${IFaceId}$/ GROUP BY time(${__interval})"
      }
     ]
    },
    {
     "title": "Network - RX:throughput",
     "type": "graph",
     "description": "Received bytes (per second)",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$col",
       "query": "SELECT MAX(\"MAX_rx_bytes_per_second\") AS \"MAX\", MEAN(\"MEAN_rx_bytes_per_second\") AS \"Mean\", MEAN(\"MEDIAN_rx_bytes_per_second\") AS \"Median\", MIN(\"MIN_rx_bytes_per_second\") AS \"MIN\" FROM \"history\".\"virt_net\" WHERE ${timeFilter} AND \"guest\" =~ /^${Guest}$/ AND \"devid\" =~ /^${IFaceId}$/ GROUP BY time(${__interval})"
      }
     ]
    }
   ]
  }
 ]
}